### ISSUE TITLE
creating payment doesn't work

### ISSUE THREAD

**Issue by MrKrakenied** [ivall/lvlup-sdk-python#1]
https://github.com/ivall/lvlup-sdk-python/blob/d110608a29a806fd74065eb807a5e385767590d2/src/payments.py#L14

Have u seen that useless comma?

**Comment by ivall** [comment]
https://stackoverflow.com/questions/997797/what-does-s-mean-in-a-python-format-string
This comma is not useless.

**Comment by MrKrakenied** [comment]
HA HA HA bro u have to fix it then

**Comment by MrKrakenied** [comment]
https://www.learnpython.org/en/String_Formatting

**Comment by pandux** [comment]
HAAHAHAHHAHAHAAHAHAHHAHAHAAHAHAHHAHAHAAHAHAHHAHAHAAHAHAHHAHAHAAHAHAHHAHAHAAHAHAHHAHAHAAHAHAHHAHAHAAHAHAHHAHAHAAHAHAHHAHAHAAHAHAHHAHAHAAHAHAHHAHAHAAHAHAHHAHAHAAHAHAHHAHAHAAHAHAHHAHAHAAHAHAHHAHAHAAHAHAHHAHAHAAHAHAHHAHAHAAHAHAHHAHAHAAHAHAHHAHAHAAHAHAHHAHAHAAHAHAHHAHAHAAHAHAHHAHAHAAHAHAHHAHAHAAHAHAHHAHAHAAHAHAHHAHAHAAHAHAHHAHAHAAHAHAHHAHAHAAHAHAHHAHAHAAHAHAHHAHAHAAHAHAHHAHAHAAHAHAHHAHA

**Comment by pandux** [comment]
sory für meine bad englisch

**Comment by Ewaldd** [comment]
hi
